insert into classificacaofiscal(ncm,descricao) values ('1234.5678','SORVETE DE MASSA')
insert into classificacaofiscal(ncm,descricao) values ('4587.9314','SORVETE DE COPO')
insert into classificacaofiscal(ncm,descricao) values ('5297.5484','SORVETE DE MASSA E COPO')
insert into classificacaofiscal(ncm,descricao) values ('1597.5344','SORVETE DE PALITO')
insert into classificacaofiscal(ncm,descricao) values ('5548.7974','COLHER DE MADEIRA')
insert into classificacaofiscal(ncm,descricao) values ('1453.4564','COPO DE PLASTICO')
